# Generated by Django 6.0.7 on 2026-08-03 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام ويزكى')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار ويشكي')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='Shop_catego_name_c2ad8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='product')),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('inventory', models.PositiveIntegerField(default=0, verbose_name=' مويوشى')),
                ('price', models.PositiveIntegerField(default=0, verbose_name=' قيمة')),
                ('off', models.PositiveIntegerField(default=0, verbose_name='')),
                ('new_price', models.PositiveIntegerField(default=0, verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Shop.category', verbose_name='category')),
                ('features', models.ManyToManyField(related_name='f_products', to='Shop.productfeature', verbose_name='')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='post_images')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='details')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Shop.products', verbose_name='')),
            ],
            options={
                'verbose_name': 'picture',
                'verbose_name_plural': 'pictures',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['created'], name='Shop_image_created_448f7a_idx')],
            },
        ),
    ]
